name: template
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scons=4.7.0
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.14.1
  - matplotlib=3.9.1
  - plotly=5.23.0
  - python-kaleido=0.2.1
  - pip:
    - graphviz==0.20.3
    - black==25.1.0
    - fredapi==0.5.2
    - linearmodels==6.1.0
