name: template
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - scons=4.10
  - numpy=2.3.3
  - pandas=2.3.3
  - scipy=1.16.2
  - scikit-learn=1.7.2
  - plotly=6.3.1
  - matplotlib=3.10.6
  - python-kaleido=0.2.1
  - pyarrow=21.0.0
  - pip
  - pip:
    - graphviz==0.21
    - black==25.9.0
    - fredapi==0.5.2
    - openpyxl==3.1.5
    - fastexcel==0.16.0
    - linearmodels==6.1.0
    - polars==1.34.0
    - fastparquet==2024.11.0
    - pikepdf==9.11.0
